include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
dart_code_metrics:
  extends:
  - recommended
  - flutter
analyzer:
  errors:
    eol_at_end_of_file: ignore
