name: furniture_store_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  collection:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  logging: ^1.3.0
  riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
