name: furniture_store_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
