import 'package:furniture_store_application/features/product/entities/entities.dart';

/// A hardcoded list of furniture items for mock purposes.
const List<FurnitureEntity> kMockFurnitureData = [
  FurnitureEntity(
    id: '1',
    name: 'Wing Chair',
    category: 'Chair',
    description:
        'Comfortable wing chair with stylish design and high-quality materials.',
    price: 199,
    imageUrl: 'assets/images/1.png',
    images: [
      'assets/images/1.png',
      'assets/images/2.png',
      'assets/images/3.png',
    ],
    colors: ['#FFCDD2', '#F8BBD0', '#E1BEE7'],
    specialOfferIds: ['summer_sale'],
    isFavorite: true,
  ),
  FurnitureEntity(
    id: '2',
    name: 'Natuzze Chair',
    category: 'Chair',
    description:
        'Modern Natuzze chair with ergonomic design and premium materials.',
    price: 150,
    imageUrl: 'assets/images/2.png',
    images: [
      'assets/images/2.png',
      'assets/images/3.png',
      'assets/images/4.png',
    ],
    colors: ['#B2EBF2', '#B3E5FC', '#BBDEFB'],
    specialOfferIds: ['summer_sale'],
  ),
  FurnitureEntity(
    id: '3',
    name: 'Arm Chair',
    category: 'Chair',
    description: 'Classic arm chair with elegant design and superior comfort.',
    price: 200,
    imageUrl: 'assets/images/3.png',
    images: [
      'assets/images/3.png',
      'assets/images/4.png',
      'assets/images/5.png',
    ],
    colors: ['#C8E6C9', '#DCEDC8', '#F0F4C3'],
  ),
  FurnitureEntity(
    id: '4',
    name: 'Modern Sofa',
    category: 'Sofa',
    description: 'Contemporary sofa with sleek design and plush cushions.',
    price: 599,
    imageUrl: 'assets/images/4.png',
    images: [
      'assets/images/4.png',
      'assets/images/5.png',
      'assets/images/6.png',
    ],
    colors: ['#FFE0B2', '#FFCCBC', '#D7CCC8'],
    specialOfferIds: ['summer_sale'],
  ),
  FurnitureEntity(
    id: '5',
    name: 'L-Shaped Sofa',
    category: 'Sofa',
    description:
        'Spacious L-shaped sofa with modern design and comfortable seating.',
    price: 899,
    imageUrl: 'assets/images/5.png',
    images: [
      'assets/images/2.png',
      'assets/images/1.png',
      'assets/images/5.png',
    ],
    colors: ['#FFE0B2', '#FFCCBC', '#D7CCC8'],
  ),
  FurnitureEntity(
    id: '6',
    name: 'Dining Table Set',
    category: 'Table',
    description:
        'Modern dining table set with stylish design and durable materials.',
    price: 799,
    imageUrl: 'assets/images/dining_table.png',
    images: [
      'assets/images/dining_table.png',
      'assets/images/dining_table_1.png',
      'assets/images/dining_table_2.png',
      'assets/images/dining_table_3.png',
      'assets/images/dining_table_4.png',
    ],
    colors: ['B2EBF2', 'B3E5FC', 'BBDEFB'],
    specialOfferIds: ['summer_sale'],
  ),
  FurnitureEntity(
    id: '7',
    name: 'Coffee Table',
    category: 'Table',
    description: 'Elegant coffee table with modern design and sturdy build.',
    price: 299,
    imageUrl: 'assets/images/coffee_table.png',
    images: [
      'assets/images/coffee_table.png',
      'assets/images/coffee_table_1.png',
    ],
    colors: ['#C8E6C9', '#DCEDC8', '#F0F4C3'],
  ),
  FurnitureEntity(
    id: '8',
    name: 'Wardrobe',
    category: 'Storage',
    description:
        'Spacious wardrobe with modern design and ample storage space.',
    price: 899,
    imageUrl: 'assets/images/wardrobe.png',
    images: [
      'assets/images/wardrobe.png',
      'assets/images/wardrobe_1.png',
      'assets/images/wardrobe_2.png',
    ],
    colors: ['#FFCDD2', '#F8BBD0', '#E1BEE7'],
    specialOfferIds: ['storage_special', 'premium_offer'],
  ),
  FurnitureEntity(
    id: '9',
    name: 'Bookshelf',
    category: 'Storage',
    description: 'Modern bookshelf with ample storage space and sleek design.',
    price: 399,
    imageUrl: 'assets/images/book_shelf.png',
    images: [
      'assets/images/book_shelf.png',
      'assets/images/book_shelf_1.png',
      'assets/images/book_shelf_2.png',
    ],
    colors: ['#B2EBF2', '#B3E5FC', '#BBDEFB'],
  ),
  FurnitureEntity(
    id: '10',
    name: 'Queen Bed',
    category: 'Bed',
    description: 'Luxurious queen bed with elegant design and sturdy frame.',
    price: 799,
    imageUrl: 'assets/images/queen_bed.png',
    images: [
      'assets/images/queen_bed.png',
      'assets/images/queen_bed_1.png',
    ],
    colors: ['#FFE0B2', '#FFCCBC', '#D7CCC8'],
  ),
  FurnitureEntity(
    id: '11',
    name: 'Single Bed',
    category: 'Bed',
    description: 'Compact single bed with modern design and sturdy frame.',
    price: 499,
    imageUrl: 'assets/images/single_bed.png',
    images: [
      'assets/images/single_bed.png',
      'assets/images/single_bed_1.png',
    ],
    colors: [
      '#FFE0B2',
      '#FFCCBC',
      '#D7CCC8',
    ],
  ),
  FurnitureEntity(
    id: '12',
    name: 'TV Cabinet',
    category: 'Storage',
    description: 'Modern TV cabinet with ample storage space and sleek design.',
    price: 499,
    imageUrl: 'assets/images/tv_cabinet.png',
    images: [
      'assets/images/tv_cabinet.png',
    ],
    colors: ['#FFCDD2', '#F8BBD0', '#E1BEE7'],
  ),
];
