// Entities
export 'entities/featured_offer_display_entity.dart';
export 'entities/special_offer_entity.dart';
// Pages
export 'pages/special_offers_page.dart';
export 'pages/special_offers_route.dart';
// Providers
export 'providers/featured_offers_provider.dart';
export 'providers/special_offer_notifier.dart';
export 'providers/special_offer_repository_provider.dart';
export 'providers/special_offer_use_case_provider.dart';
// Repositories
export 'repositories/special_offer_repository.dart';
// Sources
export 'sources/mock_special_offer_data.dart';
export 'sources/special_offer_local_data_source.dart';
// Usecases
export 'usecases/get_applicable_offets_usecase.dart';
export 'usecases/get_best_offer_usecase.dart';
export 'usecases/get_discounted_price_usecase.dart';
export 'usecases/get_featured_offers_usecase.dart';
export 'usecases/get_offers_by_ids_usecase.dart';

// Widgets
