name: application_core
description: Core package for the Furniture Store application, exporting shared dependencies and functionalities.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.0-162.1.beta
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  collection:
  fiora:
    git:
      url: https://github.com/dinmukhamednurkaliyev/fiora
      path: packages/fiora
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_svg: ^2.2.1

  freezed_annotation: ^3.1.0

  go_router: ^16.2.4
  google_fonts: ^6.3.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

flutter_gen:
  output: lib/assets/
  line_length: 80

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false

  integrations:
    image: true
    flutter_svg: true
